### ISSUE TITLE
BBMOD CLI: Vertex color does not export correctly

### ISSUE THREAD

**Issue by LocalInsomniac** [blueburn-cz/BBMOD#11]
When converting a model using BBMOD CLI with `--disable-color` set to `false`, the output does not seem to have the correct vertex colors applied to it. Analyzing the output file buffer shows that the vertex format has colors, but reading every mesh's vertex colors with `buffer_u8` returns the RGBA value of white: `255,255,255,255` and rarely cyan (which isn't visible anywhere on the model): `0,255,255,255`.

Tested on BBMOD CLI 3.1.0, input was a glTF2.0 binary model with lots of vertex colors.

**Comment by kraifpatrik** [comment]
I've tried to reproduce your issue as follows:

1. I've created a simple cube model in Blender v2.83.1 and set its vertex colors using the vertex paint tool
2. I've exported the cube model as glTF 2.0 (`Cube.glb`)
3. I've converted `Cube.glb` with BBMOD CLI 3.1.0: `BBMOD.exe Cube.glb -dn=true -dc=false` (dn to exclude normals since they're not a subject of the issue)
4.  I've loaded and rendered `Cube.bbmod` using:

ShVertexColor:
```glsl
// Vertex:
attribute vec4 in_Position;
attribute vec4 in_Color;

varying vec4 v_vColor;

void main()
{
	gl_Position = gm_Matrices[MATRIX_WORLD_VIEW_PROJECTION] * in_Position;
	v_vColor = in_Color;
}

// Fragment:
varying vec4 v_vColor;

void main()
{
	gl_FragColor = v_vColor;
}
```

Create event:
```gml
// Create a vertex format with only position and vertex colors
vformat = new BBMOD_VertexFormat(true, false, false, true);
// Create a BBMOD shader wrapper for the regular GM shader
shVertexColors = new BBMOD_Shader(ShVertexColors, vformat);
// Create a material that uses the shader
matVertexColors = new BBMOD_Material(shVertexColors);
// Load the cube model
modCube = new BBMOD_Model("Data/Cube.bbmod");
// Assign the material
modCube.Materials[0] = matVertexColors;

// Create a camera looking at the cube
camera = new BBMOD_Camera();
camera.Zoom = 5;
camera.Direction = -45;
camera.DirectionUp = -45;
```

Step event:
```gml
camera.update();
```

Draw event:
```gml
camera.apply();
bbmod_material_reset();
modCube.submit();
bbmod_material_reset();
```

And the cube renders with vertex colors as expected. Could you please try these steps with your own model? If it still does not work, there must be an issue which I cannot likely solve without the model.

PS: The vertex color is stored in GM's format ABGR, which is also used by the color constants (`c_red`, `c_green`, `c_blue`, etc.), not RGBA!

**Comment by kraifpatrik** [comment]
I've just tried it using the same version of Blender that you have and I got the same result as you. I guess that something has changed in the glTF file format? BBMOD CLI uses an older release of Assimp, so maybe that causes it. I will update it to the latest version and we will see if that helps.

**Comment by kraifpatrik** [comment]
Alright, I've tested it with Assimp v5.0.1 and v5.1.0.rc1. No luck with the former, but the latter works. If you'd like to try it out, checkout the `dev` branch.
